### ISSUE TITLE
Performance issues?

### ISSUE THREAD

**Issue by terbo** [portu/Text-FromAny#1]
Hello I've recently discovered your module, and have noticed that its speed is possibly decreased by the many use statements for the dependencies. Are there any other reports of this or could it be something else? I'm on 0.21.
I removed a few for this test and the time went down to 200ms. Could autouse be utilized? I'm looking into it.

I like the flexibility of your module and hope to be able to use it in my project, thanks!

Attached are logs from a one line test on a 5k text file:

FromANY: 0.740u 0.228s 0:00.99 96.9%     0+0k 0+0io 0pf+0w
Cat: 0.004u 0.008s 0:00.01 0.0%      0+0k 0+0io 0pf+0w
Perlslurp: 0.012u 0.024s 0:00.03 100.0%    0+0k 0+0io 0pf+0w
Perlopen: 0.008u 0.016s 0:00.02 50.0%     0+0k 0+0io 0pf+0w

**Comment by zerodogg** [comment]
Hi,
autouse is rather limited as it doesn't work with objects (and almost all of the modules used are object-oriented).
Switching from Any::Moose to Moo has a small speedup, and I'm going to push that change live soon.

I'm assuming you're benchmarking load speed and not runtime speed? Runtime should be considerably faster, especially for a cleartext file where all it does is slurp it, massage it gently (removing CR and form-feed), and then returns it.

For long-running applications (ie. Catalyst webapps) loading it all on startup is an advantage over loading them during runtime. That said it wouldn't be too hard to just split it into three files, one with the core logic, and then two classes that extend the core one - one loading everything (Text::FromAny), the other loading at runtime (Text::FromAny::Lazy?).

**Comment by zerodogg** [comment]
Ok, there's a test version of ::Lazy in the modsplit branch. Could you try that and see if it makes any differenece?

**Comment by terbo** [comment]
Will do; I did decide to use your module and have been fairly OK with it; the versatility is very useful. I will check out the new version as soon as I can, thanks!

**Comment by terbo** [comment]
I've changed servers, and now use pperl - basically a work around. 

I don't quite understand how to access ::Lazy, but I've tried the latest version from github. I guess its not such a big issue but I've started investigating using Moo too : )       Thanks.
